version: '3.1'

services:
  db:
    build: ./test_db
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_DATABASE: diary
    volumes:
        - ./test_db/data:/var/lib/mysql
    ports:
      - '23306:3306'
  web:
    build: ./main
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - ./main/diary:/diary
    ports:
      - '3000:3000'
    links:
      - db