version: '3.1'

services:
  db:
    build: ./test_db
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_DATABASE: diary
    ports:
      - '23306:3306'
  web:
    build: ./main
    volumes:
      - ./main/diary:/diary
    ports:
      - '3000:3000'
    links:
      - db